//
//  Workspace.swift
//  Team3_iOSManifests
//
//  Created by 김영훈 on 2/13/25.
//

import ProjectDescription

let workspace = Workspace(
    name: "Fitculator",
    projects: [
        "."
    ],
    schemes: [
        .scheme(
            name: "Fitculator-Workspace",
            shared: true,
            buildAction: .buildAction(targets: [
                .project(path: ".", target: "Fitculator")
            ]),
            runAction: .runAction(executable: .project(path: ".", target: "Fitculator"))
        )
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
